/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurant_s;

import javax.swing.JOptionPane;

/**
 *
 * @author computer solution
 */
public class Restaurants extends javax.swing.JFrame {
    Double firstnum,secondnum;
    String operation;

    /**
     * Creates new form Restaurants
     */
    public Restaurants() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        drinksPrice = new javax.swing.JTextField();
        deliveryPrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        mealsprice = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        subtotal = new javax.swing.JTextField();
        tax = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonreceipt = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        tex = new javax.swing.JCheckBox();
        delivery = new javax.swing.JCheckBox();
        chicken = new javax.swing.JTextField();
        mutton = new javax.swing.JTextField();
        fish = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jCheckBoxmuton = new javax.swing.JCheckBox();
        jCheckBoxfish = new javax.swing.JCheckBox();
        jCheckBoxchicken = new javax.swing.JCheckBox();
        items = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        receipt = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreareceipt = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        firstoperand = new javax.swing.JTextField();
        operator = new javax.swing.JTextField();
        display = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButtonclear = new javax.swing.JButton();
        jButtonneg = new javax.swing.JButton();
        jButtonadd = new javax.swing.JButton();
        jButtonseven = new javax.swing.JButton();
        jButtoneight = new javax.swing.JButton();
        jButtonnine = new javax.swing.JButton();
        jButtonsub = new javax.swing.JButton();
        jButtonfour = new javax.swing.JButton();
        jButtonfive = new javax.swing.JButton();
        jButtonsix = new javax.swing.JButton();
        jButtonmul = new javax.swing.JButton();
        jButtonone = new javax.swing.JButton();
        jButtontwo = new javax.swing.JButton();
        jButtonthree = new javax.swing.JButton();
        jButtondiv = new javax.swing.JButton();
        jButtonzero = new javax.swing.JButton();
        jButtondot = new javax.swing.JButton();
        jButtonequall = new javax.swing.JButton();
        jButtoninv = new javax.swing.JButton();
        jButtonsqr = new javax.swing.JButton();
        jButtonsqrt = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("     Price");

        jLabel4.setText("     Drinks");

        jLabel5.setText("     Meals");

        jLabel6.setText("     Delevery");

        drinksPrice.setEditable(false);

        deliveryPrice.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Items");

        mealsprice.setEditable(false);
        mealsprice.setText("0.0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(drinksPrice)
                    .addComponent(deliveryPrice)
                    .addComponent(mealsprice)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(drinksPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(mealsprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(deliveryPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setText(" Sub Total    :");

        jLabel9.setText(" Tax             :");

        jLabel10.setText(" Total            :");

        subtotal.setEditable(false);

        tax.setEditable(false);

        total.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(tax)
                    .addComponent(total)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 28, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setText("TOTAL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonreceipt.setText("RECEIPT");
        jButtonreceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonreceiptActionPerformed(evt);
            }
        });

        jButton3.setText("EXIT");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jButtonreceipt)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonreceipt)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tex.setText("Tax");

        delivery.setText("Home Delivery");
        delivery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deliveryMouseClicked(evt);
            }
        });

        jLabel12.setText("Drinks");

        jCheckBoxmuton.setText("Mutton");
        jCheckBoxmuton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxmutonMouseClicked(evt);
            }
        });

        jCheckBoxfish.setText("Fish");
        jCheckBoxfish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxfishMouseClicked(evt);
            }
        });

        jCheckBoxchicken.setText("Chicken");
        jCheckBoxchicken.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxchickenMouseClicked(evt);
            }
        });
        jCheckBoxchicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxchickenActionPerformed(evt);
            }
        });

        items.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select drinks", "Pepsi", "Mango", "Orange", "Banana", "Apple" }));
        items.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemsMouseClicked(evt);
            }
        });
        items.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCheckBoxchicken, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(jCheckBoxmuton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBoxfish, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fish, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                            .addComponent(mutton)
                            .addComponent(chicken)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tex, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(delivery))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(items, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 10, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chicken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxchicken))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBoxmuton)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxfish))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(items, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tex)
                    .addComponent(delivery))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextAreareceipt.setColumns(20);
        jTextAreareceipt.setRows(5);
        jScrollPane1.setViewportView(jTextAreareceipt);

        javax.swing.GroupLayout receiptLayout = new javax.swing.GroupLayout(receipt);
        receipt.setLayout(receiptLayout);
        receiptLayout.setHorizontalGroup(
            receiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
        );
        receiptLayout.setVerticalGroup(
            receiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Receipt", receipt);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        firstoperand.setEditable(false);
        firstoperand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstoperandActionPerformed(evt);
            }
        });

        operator.setEditable(false);

        jButton5.setText("<<");

        jButtonclear.setText("C");
        jButtonclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonclearActionPerformed(evt);
            }
        });

        jButtonneg.setText("+/-");
        jButtonneg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnegActionPerformed(evt);
            }
        });

        jButtonadd.setText("+");
        jButtonadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaddActionPerformed(evt);
            }
        });

        jButtonseven.setText("7");
        jButtonseven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsevenActionPerformed(evt);
            }
        });

        jButtoneight.setText("8");
        jButtoneight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoneightActionPerformed(evt);
            }
        });

        jButtonnine.setText("9");
        jButtonnine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnineActionPerformed(evt);
            }
        });

        jButtonsub.setText("-");
        jButtonsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsubActionPerformed(evt);
            }
        });

        jButtonfour.setText("4");
        jButtonfour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonfourActionPerformed(evt);
            }
        });

        jButtonfive.setText("5");
        jButtonfive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonfiveActionPerformed(evt);
            }
        });

        jButtonsix.setText("6");
        jButtonsix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsixActionPerformed(evt);
            }
        });

        jButtonmul.setText("*");
        jButtonmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmulActionPerformed(evt);
            }
        });

        jButtonone.setText("1");
        jButtonone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtononeActionPerformed(evt);
            }
        });

        jButtontwo.setText("2");
        jButtontwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontwoActionPerformed(evt);
            }
        });

        jButtonthree.setText("3");
        jButtonthree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonthreeActionPerformed(evt);
            }
        });

        jButtondiv.setText("/");
        jButtondiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondivActionPerformed(evt);
            }
        });

        jButtonzero.setText("0");
        jButtonzero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonzeroActionPerformed(evt);
            }
        });

        jButtondot.setText(".");
        jButtondot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondotActionPerformed(evt);
            }
        });

        jButtonequall.setText("=");
        jButtonequall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonequallActionPerformed(evt);
            }
        });

        jButtoninv.setText("1/x");
        jButtoninv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoninvActionPerformed(evt);
            }
        });

        jButtonsqr.setText("x^2");
        jButtonsqr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsqrActionPerformed(evt);
            }
        });

        jButtonsqrt.setText("sqrt");
        jButtonsqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsqrtActionPerformed(evt);
            }
        });

        jButton28.setText(">>");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtoninv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonzero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonfour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonseven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(firstoperand)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonsqr, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(jButtondot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtontwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonfive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtoneight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(operator)
                    .addComponent(jButtonclear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jButtonsqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jButtonthree, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtondiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jButtonsix, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonmul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jButtonneg, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonadd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(display)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jButtonnine, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonsub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButtonequall, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(71, 71, 71))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstoperand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(operator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButtonclear)
                    .addComponent(jButtonneg)
                    .addComponent(jButtonadd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonseven)
                    .addComponent(jButtoneight)
                    .addComponent(jButtonnine)
                    .addComponent(jButtonsub))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonfour)
                    .addComponent(jButtonfive)
                    .addComponent(jButtonsix)
                    .addComponent(jButtonmul))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonone)
                    .addComponent(jButtontwo)
                    .addComponent(jButtonthree)
                    .addComponent(jButtondiv))
                .addGap(4, 4, 4)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonzero)
                    .addComponent(jButtondot)
                    .addComponent(jButtonequall))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtoninv)
                    .addComponent(jButtonsqr)
                    .addComponent(jButtonsqrt)
                    .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Calculator", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField1.setText("                           RESTAURANT MANAGEMENT");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 1159, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60)))))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTextField1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(182, 182, 182))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxchickenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxchickenMouseClicked
        // TODO add your handling code here:
        int plates = Integer.parseInt(chicken.getText());
        Double mealPrice=Double.parseDouble( mealsprice.getText());
         Double chickenPrice = 85.0;
       if(jCheckBoxchicken.isSelected()){
           
        Double b = (plates * chickenPrice)+ mealPrice;
        mealsprice.setText(String.valueOf(b));
       }
       else{
           chicken.setText("0");
       }
        
    }//GEN-LAST:event_jCheckBoxchickenMouseClicked

    private void jCheckBoxmutonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxmutonMouseClicked
        // TODO add your handling code here:
         int plates = Integer.parseInt(mutton.getText());
        Double mealPrice=Double.parseDouble( mealsprice.getText());
         Double muttonPrice = 120.0;
       if(jCheckBoxmuton.isSelected()){
           
        Double b = (plates * muttonPrice)+ mealPrice;
        mealsprice.setText(String.valueOf(b));
       }else{
           mutton.setText("0");
       }
    }//GEN-LAST:event_jCheckBoxmutonMouseClicked

    private void jCheckBoxfishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxfishMouseClicked
        // TODO add your handling code here:
         int plates = Integer.parseInt(fish.getText());
        Double mealPrice=Double.parseDouble( mealsprice.getText());
         Double fishPrice = 60.0;
       if(jCheckBoxfish.isSelected()){
           
        Double b = (plates * fishPrice)+ mealPrice;
        mealsprice.setText(String.valueOf(b));
       }else{
           fish.setText("0");
       }
        
    }//GEN-LAST:event_jCheckBoxfishMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3MouseClicked

    private void deliveryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliveryMouseClicked
        // TODO add your handling code here:
        Double deliverycharge= 50.0;
      if(delivery.isSelected()){
          deliveryPrice.setText(String.valueOf(deliverycharge));
      }
    }//GEN-LAST:event_deliveryMouseClicked

    private void itemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemsMouseClicked
//useless
      
    }//GEN-LAST:event_itemsMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButtononeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtononeActionPerformed
        // TODO add your handling code here:
       String a = display.getText() + jButtonone.getText();
       display.setText(String.valueOf(a));
        
    }//GEN-LAST:event_jButtononeActionPerformed

    private void jButtontwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontwoActionPerformed
        // TODO add your handling code here:
        String a = display.getText() + jButtontwo.getText();
       display.setText(String.valueOf(a));
    }//GEN-LAST:event_jButtontwoActionPerformed

    private void jButtonthreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonthreeActionPerformed
        // TODO add your handling code here:
        String a = display.getText() + jButtonthree.getText();
       display.setText(String.valueOf(a));
    }//GEN-LAST:event_jButtonthreeActionPerformed

    private void jButtonfourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonfourActionPerformed
        // TODO add your handling code here:
        String a = display.getText() + jButtonfour.getText();
       display.setText(String.valueOf(a));
    }//GEN-LAST:event_jButtonfourActionPerformed

    private void jButtonfiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonfiveActionPerformed
        // TODO add your handling code here:
        String a = display.getText() + jButtonfive.getText();
       display.setText(String.valueOf(a));
    }//GEN-LAST:event_jButtonfiveActionPerformed

    private void jButtonsixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsixActionPerformed
        // TODO add your handling code here:
        String a = display.getText() + jButtonsix.getText();
       display.setText(String.valueOf(a));
    }//GEN-LAST:event_jButtonsixActionPerformed

    private void jButtonnineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnineActionPerformed
        // TODO add your handling code here:
        String a = display.getText() + jButtonnine.getText();
       display.setText(String.valueOf(a));
    }//GEN-LAST:event_jButtonnineActionPerformed

    private void jButtoneightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoneightActionPerformed
        // TODO add your handling code here:
        String a = display.getText() + jButtoneight.getText();
       display.setText(String.valueOf(a));
    }//GEN-LAST:event_jButtoneightActionPerformed

    private void jButtonsevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsevenActionPerformed
        // TODO add your handling code here:
        String a = display.getText() + jButtonseven.getText();
       display.setText(String.valueOf(a));
    }//GEN-LAST:event_jButtonsevenActionPerformed

    private void jButtonclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonclearActionPerformed
        // TODO add your handling code here:
         display.setText(null);
    }//GEN-LAST:event_jButtonclearActionPerformed

    private void jButtonnegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnegActionPerformed
        // TODO add your handling code here:
        Double a = Double.parseDouble(display.getText());
        a = a*(-1);
         display.setText(String.valueOf(a));
        
    }//GEN-LAST:event_jButtonnegActionPerformed

    private void jButtonaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaddActionPerformed
        // TODO add your handling code here:
        firstnum = Double.parseDouble(display.getText());
        display.setText("");
        operation = "+";
        operator.setText(operation);
        firstoperand.setText(String.valueOf(firstnum));
    }//GEN-LAST:event_jButtonaddActionPerformed

    private void firstoperandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstoperandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstoperandActionPerformed

    private void jButtonsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsubActionPerformed
        // TODO add your handling code here:
         firstnum = Double.parseDouble(display.getText());
        display.setText("");
        operation = "-";
        operator.setText(operation);
        firstoperand.setText(String.valueOf(firstnum));
    }//GEN-LAST:event_jButtonsubActionPerformed

    private void jButtonmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmulActionPerformed
        // TODO add your handling code here:
         firstnum = Double.parseDouble(display.getText());
        display.setText("");
        operation = "*";
        operator.setText(operation);
        firstoperand.setText(String.valueOf(firstnum));
    }//GEN-LAST:event_jButtonmulActionPerformed

    private void jButtondivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondivActionPerformed
        // TODO add your handling code here:
         firstnum = Double.parseDouble(display.getText());
        display.setText("");
        operation = "/";
        operator.setText(operation);
        firstoperand.setText(String.valueOf(firstnum));
    }//GEN-LAST:event_jButtondivActionPerformed

    private void jButtonzeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonzeroActionPerformed
        // TODO add your handling code here:
         String a = display.getText() + jButtonseven.getText();
       display.setText(String.valueOf(a));
    }//GEN-LAST:event_jButtonzeroActionPerformed

    private void jButtondotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondotActionPerformed
        // TODO add your handling code here:
         String a = display.getText() + jButtonseven.getText();
       display.setText(String.valueOf(a));
    }//GEN-LAST:event_jButtondotActionPerformed

    private void jButtoninvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoninvActionPerformed
        // firstnum = Double.parseDouble(display.getText()); TODO add your handling code here:
         firstnum = Double.parseDouble(display.getText());
        try{
           Double a = 1/firstnum;
             display.setText(String.valueOf(a));
              operator.setText(null);
        firstoperand.setText(String.valueOf(null));
             
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButtoninvActionPerformed

    private void jButtonsqrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsqrActionPerformed
        // TODO add your handling code here:
        firstnum = Double.parseDouble(display.getText());
        Double a = firstnum * firstnum;
        display.setText(String.valueOf(a));
              operator.setText(null);
        firstoperand.setText(String.valueOf(null));
        
        
    }//GEN-LAST:event_jButtonsqrActionPerformed

    private void jButtonsqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsqrtActionPerformed
        // TODO add your handling code here:
          firstnum = Double.parseDouble(display.getText());
          Double a = Math.sqrt(firstnum);
           display.setText(String.valueOf(a));
                  operator.setText(null);
        firstoperand.setText(String.valueOf(null));
        
    }//GEN-LAST:event_jButtonsqrtActionPerformed

    private void jButtonequallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonequallActionPerformed
        // TODO add your handling code here:
        secondnum = Double.parseDouble(display.getText());
        switch(operation){
            case "+":
              Double  a = firstnum + secondnum;
              display.setText(String.valueOf(a));
              operator.setText(null);
              firstoperand.setText(null);
                break;
                 case "-" :
                 Double  b= firstnum - secondnum; 
              display.setText(String.valueOf(b));
              operator.setText(null);
              firstoperand.setText(null);
                break;
                 case "*" :
                     Double  c ;
        c = firstnum * secondnum;
              display.setText(String.valueOf(c));
              operator.setText(null);
              firstoperand.setText(null);
                break;
                 case "/":
                     try{
                     Double d ;
           d = firstnum / secondnum;
              display.setText(String.valueOf(d));
              operator.setText(null);
              firstoperand.setText(null);
                     }catch(Exception e){
                          JOptionPane.showMessageDialog(null, e);
                     }
        }
    }//GEN-LAST:event_jButtonequallActionPerformed

    private void jButtonreceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonreceiptActionPerformed
        // TODO add your handling code here:
        Double chickens = Double.parseDouble(chicken.getText());
        Double muttons = Double.parseDouble(mutton.getText());
        Double fishes= Double.parseDouble(fish.getText());
        jTextAreareceipt.append("***** Restaurant Management Receipt *****\n"+"chicken Plate  :"+chickens+"\t"+ chickens*85.0+"\n"  +"Mutton plate :"+muttons+"\t"+muttons*120.0+"\n"+"Fish plate :"+fishes+"\t\t"+fishes*60.0+"\n"+"Delivery charge : "+"\t"+50.0+"\n"+"Tax :"+tax.getText()+"\n"+"Total :"+"\t"+total.getText()+"\n"+"*****Thanks for visiting*****");
        
        
    }//GEN-LAST:event_jButtonreceiptActionPerformed

    private void itemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemsActionPerformed
        // TODO add your handling code here:
         Double Selectdrinks, Pepsi, Mango, Orange, Banana, Apple;
        Pepsi = 15.0;
        Mango=40.0;
        Orange = 25.0;
        Banana = 20.0;
        Apple = 45.0;
        
        if(items.getSelectedItem().equals("Pepsi")){
            //Double a = Double.parseDouble( drinksPrice.getText())+Pepsi;
            drinksPrice.setText(String.valueOf(Pepsi));
        }
        if(items.getSelectedItem().equals("Mango")){
         // Double b = Double.parseDouble( drinksPrice.getText());
         // Double c = b + Mango;
            drinksPrice.setText(String.valueOf(Mango));
        }
        if(items.getSelectedItem().equals("Orange")){
          // Double a = Double.parseDouble( drinksPrice.getText())+ Double.parseDouble(String.valueOf(Orange));
            drinksPrice.setText(String.valueOf(Orange));
        }
        if(items.getSelectedItem().equals("Banana")){
           // Double a = Double.parseDouble( drinksPrice.getText())+ Double.parseDouble(String.valueOf(Banana));
            drinksPrice.setText(String.valueOf(Banana));
        }
        if(items.getSelectedItem().equals("Apple")){
            //Double a = Double.parseDouble( drinksPrice.getText())+ Double.parseDouble(String.valueOf(Apple));
            drinksPrice.setText(String.valueOf(Apple));
        }
    }//GEN-LAST:event_itemsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Double drinkprice = Double.parseDouble( drinksPrice.getText());
        Double mealprint = Double.parseDouble( mealsprice.getText());
        Double deliverycharge = Double.parseDouble( deliveryPrice.getText());
        Double subcharges=drinkprice + mealprint + deliverycharge;
        subtotal.setText(String.valueOf(subcharges));
      Double taxes = (subcharges *6)/100;
        tax.setText(String.valueOf(taxes));
        subcharges= subcharges + taxes;
        total.setText(String.valueOf(subcharges));
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        chicken.setText(null);
        mutton.setText(null);
        subtotal.setText(null);
        tax.setText(null);
        total.setText(null);
        mealsprice.setText(null);
        jTextAreareceipt.setText(null);
    // delivery.isSelected(false);
    deliveryPrice.setText(null);
   display.setText(null);
   drinksPrice.setText(null);
    firstoperand.setText(null);
   fish.setText(null);
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBoxchickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxchickenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxchickenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurants().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField chicken;
    private javax.swing.JCheckBox delivery;
    private javax.swing.JTextField deliveryPrice;
    private javax.swing.JTextField display;
    private javax.swing.JTextField drinksPrice;
    private javax.swing.JTextField firstoperand;
    private javax.swing.JTextField fish;
    private javax.swing.JComboBox<String> items;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonadd;
    private javax.swing.JButton jButtonclear;
    private javax.swing.JButton jButtondiv;
    private javax.swing.JButton jButtondot;
    private javax.swing.JButton jButtoneight;
    private javax.swing.JButton jButtonequall;
    private javax.swing.JButton jButtonfive;
    private javax.swing.JButton jButtonfour;
    private javax.swing.JButton jButtoninv;
    private javax.swing.JButton jButtonmul;
    private javax.swing.JButton jButtonneg;
    private javax.swing.JButton jButtonnine;
    private javax.swing.JButton jButtonone;
    private javax.swing.JButton jButtonreceipt;
    private javax.swing.JButton jButtonseven;
    private javax.swing.JButton jButtonsix;
    private javax.swing.JButton jButtonsqr;
    private javax.swing.JButton jButtonsqrt;
    private javax.swing.JButton jButtonsub;
    private javax.swing.JButton jButtonthree;
    private javax.swing.JButton jButtontwo;
    private javax.swing.JButton jButtonzero;
    private javax.swing.JCheckBox jCheckBoxchicken;
    private javax.swing.JCheckBox jCheckBoxfish;
    private javax.swing.JCheckBox jCheckBoxmuton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextArea jTextAreareceipt;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField mealsprice;
    private javax.swing.JTextField mutton;
    private javax.swing.JTextField operator;
    private javax.swing.JPanel receipt;
    private javax.swing.JTextField subtotal;
    private javax.swing.JTextField tax;
    private javax.swing.JCheckBox tex;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
